from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from django.shortcuts import get_object_or_404
from django.utils import timezone
from datetime import timedelta

from .models import LogDay, DutySegment
from .serializers import (
    LogDaySerializer,
    LogDayListSerializer,
    DutySegmentSerializer,
    TripLogsSerializer,
    HOSStatusSerializer,
)
from .selectors import get_trip_logs, get_log_day_with_segments, get_driver_hos_status
from core.trips.models import Trip
from core.drivers.models import Driver


class LogDayViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API endpoints for viewing log days.
    
    These are read-only because logs are generated by the HOS engine,
    not created manually.
    
    Endpoints:
    - GET /logs/days/ - List all log days (with optional date filtering)
    - GET /logs/days/{id}/ - Get a specific log day with segments
    - GET /logs/days/trip/{trip_id}/ - Get all logs for a trip
    - GET /logs/days/hos-status/ - Get current HOS status for a driver
    """
    
    queryset = LogDay.objects.all().select_related('trip', 'trip__driver')
    permission_classes = [AllowAny]
    
    def get_serializer_class(self):
        """Use different serializers for list vs detail."""
        if self.action == 'list':
            return LogDayListSerializer
        return LogDaySerializer
    
    def get_queryset(self):
        """Optimize queries and handle date filtering."""
        queryset = super().get_queryset()
        
        if self.action == 'retrieve':
            queryset = LogDay.objects.prefetch_related('segments')
        
        # Date range filtering for list action
        if self.action == 'list':
            start_date = self.request.query_params.get('start_date')
            end_date = self.request.query_params.get('end_date')
            driver_id = self.request.query_params.get('driver_id')
            
            if start_date:
                queryset = queryset.filter(date__gte=start_date)
            if end_date:
                queryset = queryset.filter(date__lte=end_date)
            if driver_id:
                queryset = queryset.filter(trip__driver_id=driver_id)
        
        return queryset
    
    @action(detail=False, methods=['get'], url_path='trip/(?P<trip_id>[^/.]+)')
    def trip(self, request, trip_id=None):
        """
        Get all logs for a specific trip.
        
        GET /logs/days/trip/{trip_id}/
        
        Returns complete log data for the trip:
        - Trip metadata
        - All log days with segments
        - Summary statistics
        
        This is the main endpoint the frontend uses to render logs.
        """
        
        try:
            trip_logs = get_trip_logs(int(trip_id))
            serializer = TripLogsSerializer(trip_logs)
            return Response(serializer.data)
        
        except Trip.DoesNotExist:
            return Response(
                {
                    'status': 'error',
                    'message': f'Trip {trip_id} not found'
                },
                status=status.HTTP_404_NOT_FOUND
            )
        
        except ValueError:
            return Response(
                {
                    'status': 'error',
                    'message': 'Invalid trip ID'
                },
                status=status.HTTP_400_BAD_REQUEST
            )
    
    @action(detail=False, methods=['get'], url_path='hos-status')
    def hos_status(self, request):
        """
        Get current HOS (Hours of Service) status.
        
        GET /logs/days/hos-status/?driver_id=1
        
        Returns remaining driving hours, on-duty window, cycle hours,
        and when breaks/rest are required.
        
        If no driver_id is provided, uses driver_id=1 as default.
        """
        
        driver_id = request.query_params.get('driver_id', 1)
        
        try:
            driver = Driver.objects.get(id=int(driver_id))
            hos_status = get_driver_hos_status(driver)
            serializer = HOSStatusSerializer(hos_status)
            return Response(serializer.data)
        
        except Driver.DoesNotExist:
            return Response(
                {
                    'status': 'error',
                    'message': f'Driver {driver_id} not found'
                },
                status=status.HTTP_404_NOT_FOUND
            )
        
        except ValueError:
            return Response(
                {
                    'status': 'error',
                    'message': 'Invalid driver ID'
                },
                status=status.HTTP_400_BAD_REQUEST
            )


class DutySegmentViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API endpoints for viewing individual duty segments.
    
    These are read-only.
    
    Endpoints:
    - GET /segments/ - List all segments
    - GET /segments/{id}/ - Get a specific segment
    """
    
    queryset = DutySegment.objects.all().select_related('log_day', 'log_day__trip')
    serializer_class = DutySegmentSerializer
    permission_classes = [AllowAny]
