# Generated by Django 4.2 on 2026-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Driver's full name", max_length=255)),
                ('cycle_type', models.CharField(choices=[('70_8', '70 hours / 8 days')], default='70_8', help_text='HOS cycle type - determines rolling hour limit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this driver record was created')),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['name'],
            },
        ),
    ]
