# Generated by Django 4.2 on 2026-01-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date for this log (local time zone aware)')),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours in DRIVING status', max_digits=5)),
                ('total_on_duty_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours in ON_DUTY status (not including driving)', max_digits=5)),
                ('total_off_duty_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours in OFF_DUTY status', max_digits=5)),
                ('total_sleeper_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours in SLEEPER status', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this log was generated')),
                ('trip', models.ForeignKey(help_text='Trip this log day belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='log_days', to='trips.trip')),
            ],
            options={
                'db_table': 'log_days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When this duty status began (UTC)')),
                ('end_time', models.DateTimeField(help_text='When this duty status ended (UTC)')),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty Not Driving')], help_text='FMCSA duty status', max_length=20)),
                ('city', models.CharField(blank=True, help_text='City where status change occurred', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State where status change occurred', max_length=50)),
                ('remark', models.CharField(blank=True, help_text="Description of activity (e.g., 'Pickup', 'Fuel stop', '30-min break')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this segment was created')),
                ('log_day', models.ForeignKey(help_text='LogDay this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='logs.logday')),
            ],
            options={
                'db_table': 'duty_segments',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='logday',
            index=models.Index(fields=['trip', 'date'], name='log_days_trip_id_1b7349_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='logday',
            unique_together={('trip', 'date')},
        ),
        migrations.AddIndex(
            model_name='dutysegment',
            index=models.Index(fields=['log_day', 'start_time'], name='duty_segmen_log_day_5697e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dutysegment',
            index=models.Index(fields=['status'], name='duty_segmen_status_ff394e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dutysegment',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='end_after_start'),
        ),
    ]
