# Generated by Django 4.2 on 2026-01-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current processing status of the trip', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is FAILED', null=True)),
                ('current_location', models.CharField(help_text='Where the driver is starting from (city, state)', max_length=255)),
                ('pickup_location', models.CharField(help_text='Where to pick up the load', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Where to deliver the load', max_length=255)),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, help_text='Hours already used in current 70-hour/8-day cycle', max_digits=5)),
                ('planned_start_time', models.DateTimeField(help_text='When the driver plans to start this trip (UTC)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this trip was planned')),
                ('total_miles', models.PositiveIntegerField(blank=True, help_text='Total trip distance in miles (cached for regeneration)', null=True)),
                ('average_speed_mph', models.PositiveSmallIntegerField(blank=True, help_text='Average speed used for planning (cached for regeneration)', null=True)),
                ('driver', models.ForeignKey(help_text='Driver making this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
